# Generated by Django 3.2.15 on 2022-09-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Image', models.CharField(max_length=2083)),
                ('Description', models.TextField()),
                ('Instructions', models.TextField()),
                ('Ingredients', models.TextField()),
                ('PrepTime', models.CharField(max_length=5)),
                ('CookTime', models.CharField(max_length=5)),
                ('Servings', models.CharField(max_length=5)),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Image', models.CharField(max_length=2083)),
                ('Description', models.TextField()),
                ('Instructions', models.TextField()),
                ('Ingredients', models.TextField()),
                ('PrepTime', models.CharField(max_length=5)),
                ('CookTime', models.CharField(max_length=5)),
                ('Servings', models.CharField(max_length=5)),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Image', models.CharField(max_length=2083)),
                ('Description', models.TextField()),
                ('Instructions', models.TextField()),
                ('Ingredients', models.TextField()),
                ('PrepTime', models.CharField(max_length=5)),
                ('CookTime', models.CharField(max_length=5)),
                ('Servings', models.CharField(max_length=5)),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Image', models.CharField(max_length=2083)),
                ('Description', models.TextField()),
                ('Instructions', models.TextField()),
                ('Ingredients', models.TextField()),
                ('PrepTime', models.CharField(max_length=5)),
                ('CookTime', models.CharField(max_length=5)),
                ('Servings', models.CharField(max_length=5)),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MainMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Image', models.CharField(max_length=2083)),
                ('Description', models.TextField()),
                ('Instructions', models.TextField()),
                ('Ingredients', models.TextField()),
                ('PrepTime', models.CharField(max_length=5)),
                ('CookTime', models.CharField(max_length=5)),
                ('Servings', models.CharField(max_length=5)),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PatriesandBakery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Image', models.CharField(max_length=2083)),
                ('Description', models.TextField()),
                ('Instructions', models.TextField()),
                ('Ingredients', models.TextField()),
                ('PrepTime', models.CharField(max_length=5)),
                ('CookTime', models.CharField(max_length=5)),
                ('Servings', models.CharField(max_length=5)),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Image', models.CharField(max_length=2083)),
                ('Description', models.TextField()),
                ('Instructions', models.TextField()),
                ('Ingredients', models.TextField()),
                ('PrepTime', models.CharField(max_length=5)),
                ('CookTime', models.CharField(max_length=5)),
                ('Servings', models.CharField(max_length=5)),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Starch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Image', models.CharField(max_length=2083)),
                ('Description', models.TextField()),
                ('Instructions', models.TextField()),
                ('Ingredients', models.TextField()),
                ('PrepTime', models.CharField(max_length=5)),
                ('CookTime', models.CharField(max_length=5)),
                ('Servings', models.CharField(max_length=5)),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vegan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Image', models.CharField(max_length=2083)),
                ('Description', models.TextField()),
                ('Instructions', models.TextField()),
                ('Ingredients', models.TextField()),
                ('PrepTime', models.CharField(max_length=5)),
                ('CookTime', models.CharField(max_length=5)),
                ('Servings', models.CharField(max_length=5)),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
            ],
        ),
    ]
