# Generated by Django 3.2.15 on 2022-09-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220914_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitings',
            name='Image',
            field=models.ImageField(max_length=2083, upload_to=''),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='Image',
            field=models.ImageField(max_length=2083, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='Image',
            field=models.ImageField(max_length=2083, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='Image',
            field=models.ImageField(max_length=2083, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mainmeal',
            name='Image',
            field=models.ImageField(max_length=2083, upload_to=''),
        ),
        migrations.AlterField(
            model_name='patriesandbakery',
            name='Image',
            field=models.ImageField(max_length=2083, upload_to=''),
        ),
        migrations.AlterField(
            model_name='starch',
            name='Image',
            field=models.ImageField(max_length=2083, upload_to=''),
        ),
        migrations.AlterField(
            model_name='vegan',
            name='Image',
            field=models.ImageField(max_length=2083, upload_to=''),
        ),
    ]
