# Generated by Django 3.2.15 on 2022-09-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_recipes_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Image',
            field=models.ImageField(upload_to='Images'),
        ),
    ]
