# Generated by Django 3.2.15 on 2022-09-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_rename_mainmeal_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Single',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Image', models.ImageField(max_length=2083, upload_to='')),
                ('Description', models.TextField()),
                ('Instructions', models.TextField()),
                ('Ingredients', models.TextField()),
                ('PrepTime', models.CharField(max_length=5)),
                ('CookTime', models.CharField(max_length=5)),
                ('Servings', models.CharField(max_length=5)),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
            ],
        ),
    ]
