# Generated by Django 3.2.15 on 2022-09-21 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_single'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Single',
        ),
    ]
