# Generated by Django 3.2.15 on 2022-09-24 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meal',
            new_name='Meals',
        ),
    ]
