# Generated by Django 3.2.15 on 2022-09-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_rename_meal_meals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dinner',
            new_name='Fish',
        ),
        migrations.RenameModel(
            old_name='Lunch',
            new_name='Meat',
        ),
    ]
