# Generated by Django 3.2.15 on 2022-09-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20220924_1449'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meals',
            new_name='Chicken',
        ),
    ]
